#' Build Data Quality Flags
#'
#' Performs automated quality review checks across uploaded datasets.
#'
#' Checks include:
#' \itemize{
#'   \item Missingness
#'   \item Duplicate index values
#'   \item Cardinality assessment
#'   \item Sentinel value detection
#'   \item Numeric outlier review
#'   \item Date review
#' }
#'
#' @param datasets A named list of datasets.
#' @param index_vars Optional character vector containing
#' subject or index variables.
#' @param high_missing_cutoff Missingness threshold percentage.
#' @param high_cardinality_cutoff Cardinality threshold.
#'
#' @return Data frame containing quality review findings.
#'
#' @export
#' 
build_quality_flags <- function(datasets, index_vars = character(), high_missing_cutoff = 20, high_cardinality_cutoff = 50) {
  flags <- list()
  add_flag <- function(dataset, variable, check_type, severity, issue, detail) {
    tibble::tibble(dataset = dataset, variable = variable, check_type = check_type, severity = severity, issue = issue, detail = detail)
  }
  for (ds in names(datasets)) {
    df <- datasets[[ds]]
    if (nrow(df) == 0) {
      flags[[length(flags) + 1]] <- add_flag(ds, "<dataset>", "Dataset structure", "High", "Empty dataset", "Dataset has 0 rows.")
      next
    }
    idx_names <- names(df)[toupper(names(df)) %in% toupper(index_vars)]
    if (length(idx_names) > 0) {
      for (idx in idx_names) {
        dup_n <- sum(duplicated(df[[idx]]) & !is.na(df[[idx]]))
        if (dup_n > 0) flags[[length(flags) + 1]] <- add_flag(ds, idx, "Duplicate index", "High", "Duplicate subject/index values", paste0(dup_n, " duplicated row(s) based on ", idx, "."))
      }
    }
    for (v in names(df)) {
      x <- df[[v]]
      n <- length(x)
      miss_n <- sum(is.na(x))
      miss_pct <- ifelse(n == 0, NA_real_, 100 * miss_n / n)
      distinct_nonmissing <- dplyr::n_distinct(x, na.rm = TRUE)
      distinct_all <- dplyr::n_distinct(x, na.rm = FALSE)
      if (!is.na(miss_pct) && miss_pct >= high_missing_cutoff) {
        flags[[length(flags) + 1]] <- add_flag(ds, v, "Missingness", ifelse(miss_pct >= 50, "High", "Medium"), "High missingness", paste0(format(round(miss_pct, 1), nsmall = 1), "% missing (", miss_n, " of ", n, ")."))
      }
      if (distinct_nonmissing <= 1) flags[[length(flags) + 1]] <- add_flag(ds, v, "Cardinality", "Medium", "Constant or near-constant variable", paste0("Non-missing distinct values: ", distinct_nonmissing, "."))
      if (!is.numeric(x) && distinct_all > high_cardinality_cutoff) flags[[length(flags) + 1]] <- add_flag(ds, v, "Cardinality", "Low", "High-cardinality character variable", paste0("Distinct values including missing: ", distinct_all, "."))
      char_x <- as.character(x)
      sentinels <- c("7777", "9999", "07/07/7777", "09/09/9999", "UNKNOWN", "UNK", "NA")
      for (s in sentinels) {
        s_count <- sum(toupper(char_x) == toupper(s), na.rm = TRUE)
        if (s_count > 0) flags[[length(flags) + 1]] <- add_flag(ds, v, "Sentinel values", "Low", paste0("Sentinel value detected: ", s), paste0(s_count, " occurrence(s)."))
      }
      if (is.numeric(x)) {
        vals <- x[!is.na(x)]
        if (length(vals) >= 5) {
          q1 <- stats::quantile(vals, 0.25, names = FALSE)
          q3 <- stats::quantile(vals, 0.75, names = FALSE)
          iqr <- q3 - q1
          if (!is.na(iqr) && iqr > 0) {
            lo <- q1 - 1.5 * iqr
            hi <- q3 + 1.5 * iqr
            out_n <- sum(vals < lo | vals > hi, na.rm = TRUE)
            if (out_n > 0) flags[[length(flags) + 1]] <- add_flag(ds, v, "Numeric review", "Low", "Potential outliers", paste0(out_n, " value(s) outside 1.5*IQR range [", signif(lo, 6), ", ", signif(hi, 6), "]."))
          }
        }
      }
      if (grepl("DT|DATE|DTC", toupper(v))) {
        sentinel_date_count <- sum(char_x %in% c("07/07/7777", "09/09/9999", "7777-07-07", "9999-09-09"), na.rm = TRUE)
        if (sentinel_date_count > 0) flags[[length(flags) + 1]] <- add_flag(ds, v, "Date review", "Medium", "Sentinel date detected", paste0(sentinel_date_count, " sentinel date value(s)."))
      }
    }
  }
  if (length(flags) == 0) return(tibble::tibble(dataset = character(), variable = character(), check_type = character(), severity = character(), issue = character(), detail = character()))
  dplyr::bind_rows(flags)
}
#' Summarize Quality Flags
#'
#' Produces a summary of quality review findings grouped
#' by severity and review category.
#'
#' @param flags Output generated by
#' \code{build_quality_flags()}.
#'
#' @return Data frame summarizing issue counts by
#' severity and check type.
#'
#' @export.
#'
quality_flag_summary <- function(flags) {
  if (nrow(flags) == 0) return(tibble::tibble(severity = character(), check_type = character(), issue_count = integer()))
  flags |> dplyr::count(severity, check_type, name = "issue_count") |> dplyr::arrange(factor(severity, levels = c("High", "Medium", "Low")), dplyr::desc(issue_count))
}
