excel_hyperlink_formula <- function(sheet, display_text) {
  sheet_escaped <- gsub("'", "''", sheet, fixed = TRUE)
  text_escaped <- gsub("\"", "\"\"", display_text, fixed = TRUE)
  
  paste0(
    "=HYPERLINK(\"#'",
    sheet_escaped,
    "'!A1\", \"",
    text_escaped,
    "\")"
  )
}

write_back_to_index <- function(wb, sheet, link_style) {
  openxlsx::writeFormula(wb, sheet, x = excel_hyperlink_formula("Index", "<< Back to Index"), startRow = 1, startCol = 2)
  openxlsx::addStyle(wb, sheet, link_style, rows = 1, cols = 2, gridExpand = TRUE, stack = TRUE)
}

write_simple_sheet <- function(wb, sheet, title, dat, header_style, body_style, title_style, link_style, index_adder, description, widths = NULL) {
  sh <- make_unique_sheet(wb, sheet)
  openxlsx::addWorksheet(wb, sh)
  openxlsx::showGridLines(wb, sh, showGridLines = FALSE)
  index_adder(sh, description)
  openxlsx::writeData(wb, sh, title, startRow = 1, startCol = 1)
  openxlsx::addStyle(wb, sh, title_style, rows = 1, cols = 1, stack = TRUE)
  write_back_to_index(wb, sh, link_style)
  dat <- clean_excel_df(dat)
  if (is.null(dat) || nrow(dat) == 0) {
    openxlsx::writeData(wb, sh, "No records available.", startRow = 3, startCol = 1)
    openxlsx::addStyle(wb, sh, body_style, rows = 3, cols = 1, stack = TRUE)
  } else {
    openxlsx::writeData(wb, sh, dat, startRow = 3, startCol = 1, headerStyle = header_style)
    openxlsx::addStyle(wb, sh, body_style, rows = 4:(3 + nrow(dat)), cols = 1:ncol(dat), gridExpand = TRUE, stack = TRUE)
    if (is.null(widths)) widths <- rep(22, ncol(dat))
    openxlsx::setColWidths(wb, sh, cols = 1:ncol(dat), widths = widths)
    openxlsx::freezePane(wb, sh, firstActiveRow = 4)
  }
  sh
}

#' Write Specification Workbook
#'
#' Generates the Excel workbook produced by Data Specs Reviewer.
#'
#' The workbook may contain:
#' \itemize{
#'   \item Index
#'   \item Library Summary
#'   \item Variable Summary
#'   \item Dataset Specifications
#'   \item Quality Flags
#'   \item Missingness Review
#'   \item Numeric Review
#'   \item Sentinel Value Review
#'   \item Cardinality Review
#' }
#'
#' @param specs Output generated by
#' \code{build_specs()}.
#' @param file Output Excel filename.
#' @param lib_name Library name shown in the workbook.
#' @param quality_flags Output generated by
#' \code{build_quality_flags()}.
#'
#' @return Invisibly returns the workbook path.
#'
#' @export
#' 
write_specs_workbook <- function(specs, file, lib_name = "MYDATA", quality_flags = NULL) {
  lib_name <- toupper(safe_name(or_else(lib_name, "MYDATA")))
  if (nchar(lib_name) == 0) lib_name <- "MYDATA"
  wb <- openxlsx::createWorkbook()

  title_style <- openxlsx::createStyle(textDecoration = "bold", fontSize = 9, fontName = "Times New Roman", fontColour = "#1F4E79", wrapText = TRUE)
  subtitle_style <- openxlsx::createStyle(textDecoration = "bold", fontSize = 9, fontName = "Times New Roman", fontColour = "#000000", wrapText = TRUE)
  # header_style <- openxlsx::createStyle(textDecoration = "bold", fgFill = "#D9EAF7", border = "TopBottomLeftRight", borderColour = "#9EADCC", halign = "center", valign = "center", fontSize = 9, fontName = "Arial", wrapText = TRUE)
  # body_style <- openxlsx::createStyle(fontSize = 9, fontName = "Times New Roman", border = "TopBottomLeftRight", borderColour = "#F2F2F2", valign = "top", wrapText = TRUE)
  spec_header_style <- openxlsx::createStyle(fontSize = 9, fontName = "Times New Roman", textDecoration = "bold", halign = "center", valign = "center", wrapText = TRUE)
  # spec_block_white <- openxlsx::createStyle(fontSize = 9, fontName = "Times New Roman", valign = "top", wrapText = TRUE)
  # spec_block_gray <- openxlsx::createStyle(fontSize = 9, fontName = "Times New Roman", fgFill = "#F2F2F2", valign = "top", wrapText = TRUE)
  # spec_variable_row_style <- openxlsx::createStyle(fontSize = 9, fontName = "Times New Roman", textDecoration = "bold", valign = "top", wrapText = TRUE)

  header_style <- openxlsx::createStyle(
    textDecoration = "bold",
    fgFill = "#D9EAF7",
    border = "Top",
    borderColour = "#808080",
    halign = "center",
    valign = "center",
    fontSize = 9,
    fontName = "Arial",
    wrapText = TRUE
  )
  
  body_style <- openxlsx::createStyle(
    fontSize = 9,
    fontName = "Times New Roman",
    border = "TopBottomLeftRight",
    borderColour = "#D9D9D9",
    valign = "top",
    wrapText = TRUE
  )
  
  spec_block_white <- openxlsx::createStyle(
    fontSize = 9,
    fontName = "Times New Roman",
    border = "TopBottomLeftRight",
    borderColour = "#D9D9D9",
    valign = "top",
    wrapText = TRUE
  )
  
  spec_block_gray <- openxlsx::createStyle(
    fontSize = 9,
    fontName = "Times New Roman",
    fgFill = "#F2F2F2",
    border = "TopBottomLeftRight",
    borderColour = "#D9D9D9",
    valign = "top",
    wrapText = TRUE
  )
  
  spec_variable_row_style <- openxlsx::createStyle(
    fontSize = 9,
    fontName = "Times New Roman",
    textDecoration = "bold",
    border = "TopBottomLeftRight",
    borderColour = "#A6A6A6",
    valign = "top",
    wrapText = TRUE
  )
  
  credit_style <- openxlsx::createStyle(fontSize = 8, fontName = "Times New Roman", fontColour = "#666666", wrapText = TRUE, valign = "top")
  link_style <- openxlsx::createStyle(fontSize = 9, fontName = "Times New Roman", fontColour = "#0563C1", textDecoration = "underline")

  openxlsx::addWorksheet(wb, "Index")
  openxlsx::writeData(wb, "Index", "Data Specs Reviewer - Workbook Index", startRow = 1, startCol = 1)
  openxlsx::addStyle(wb, "Index", title_style, rows = 1, cols = 1, stack = TRUE)
  index_rows <- list()
  add_index_row <- function(sheet_name, description) {
    index_rows[[length(index_rows) + 1]] <<- tibble::tibble(Sheet = sheet_name, Description = description)
  }

  summary_sheet <- make_unique_sheet(wb, paste0("Library ", lib_name, " - Summary"))
  openxlsx::addWorksheet(wb, summary_sheet)
  add_index_row(summary_sheet, paste0("Summary of datasets within library ", lib_name))
  openxlsx::writeData(wb, summary_sheet, paste0("Summary of Datasets within Library - ", lib_name), startRow = 1, startCol = 1)
  openxlsx::addStyle(wb, summary_sheet, title_style, rows = 1, cols = 1, gridExpand = TRUE)
  write_back_to_index(wb, summary_sheet, link_style)

  lib_out <- dplyr::transmute(specs$lib_summary, `Data Set Name` = dataset, Observations = observations, `Unique Index Values` = unique_index_values, `Number of Variables` = variables)
  lib_out <- clean_excel_df(lib_out)
  openxlsx::writeData(wb, summary_sheet, lib_out, startRow = 3, startCol = 1, headerStyle = header_style)
  if (nrow(lib_out) > 0) openxlsx::addStyle(wb, summary_sheet, body_style, rows = 4:(3 + nrow(lib_out)), cols = 1:ncol(lib_out), gridExpand = TRUE, stack = TRUE)

  start_var <- nrow(lib_out) + 6
  openxlsx::writeData(wb, summary_sheet, "Variables that Exist Across Multiple Datasets", startRow = start_var, startCol = 1)
  openxlsx::addStyle(wb, summary_sheet, subtitle_style, rows = start_var, cols = 1, gridExpand = TRUE)
  var_out <- dplyr::transmute(specs$var_summary, `Variable Name` = variable_name, `Datasets Containing Variable` = datasets_containing_variable, `Variable Label(s)` = labels)
  var_out <- clean_excel_df(var_out)
  openxlsx::writeData(wb, summary_sheet, var_out, startRow = start_var + 2, startCol = 1, headerStyle = header_style)
  if (nrow(var_out) > 0) openxlsx::addStyle(wb, summary_sheet, body_style, rows = (start_var + 3):(start_var + 2 + nrow(var_out)), cols = 1:ncol(var_out), gridExpand = TRUE, stack = TRUE)
  credit_row <- start_var + nrow(var_out) + 5
  credit_text <- paste("Credits:", "Inspired by the work of Jeffrey Meyers.", "Shiny app author: Prasanth V.P <prasanth.stat@gmail.com>", sep = "\n")
  openxlsx::writeData(wb, summary_sheet, credit_text, startRow = credit_row, startCol = 1)
  openxlsx::addStyle(wb, summary_sheet, credit_style, rows = credit_row, cols = 1:4, gridExpand = TRUE, stack = TRUE)
  openxlsx::setColWidths(wb, summary_sheet, cols = 1:5, widths = c(35, 44, 22, 22, 5))
  openxlsx::freezePane(wb, summary_sheet, firstActiveRow = 3)

  dsets <- unique(specs$specs_condensed$dataset)
  for (ds in dsets) {
    sh <- make_unique_sheet(wb, paste0("Dataset - ", ds))
    openxlsx::addWorksheet(wb, sh)
    openxlsx::showGridLines(wb, sh, showGridLines = FALSE)
    add_index_row(sh, paste0("Specification details for dataset ", ds))
    openxlsx::writeData(wb, sh, paste0("Dataset Name: ", clean_one_text(ds)), startRow = 1, startCol = 1)
    openxlsx::addStyle(wb, sh, title_style, rows = 1, cols = 1, gridExpand = TRUE)
    write_back_to_index(wb, sh, link_style)
    dat <- specs$specs_long |> dplyr::filter(dataset == ds) |> dplyr::select(Specification = spec, Value = value)
    dat <- clean_excel_df(dat)
    openxlsx::writeData(wb, sh, dat, startRow = 3, startCol = 1, headerStyle = spec_header_style, borders = "none")
    openxlsx::setColWidths(wb, sh, cols = 1, widths = 35)
    openxlsx::setColWidths(wb, sh, cols = 2, widths = 44)
    if (nrow(dat) > 0) {
      first_data_row <- 4
      last_data_row <- 3 + nrow(dat)
      block_starts <- seq(first_data_row, last_data_row, by = 4)
      for (b in seq_along(block_starts)) {
        block_rows <- block_starts[b]:(block_starts[b] + 3)
        block_rows <- block_rows[block_rows <= last_data_row]
        block_style <- if (b %% 2 == 0) spec_block_gray else spec_block_white
        openxlsx::addStyle(wb, sh, block_style, rows = block_rows, cols = 1:2, gridExpand = TRUE, stack = TRUE)
      }
      variable_rows <- seq(first_data_row, last_data_row, by = 4)
      openxlsx::addStyle(wb, sh, spec_variable_row_style, rows = variable_rows, cols = 1:2, gridExpand = TRUE, stack = TRUE)
      row_heights <- vapply(seq_len(nrow(dat)), function(i) {
        spec_i <- as.character(dat$Specification[i])
        value_i <- as.character(dat$Value[i])
        if (is.na(value_i)) value_i <- ""
        if (spec_i == "Values") estimate_excel_row_height(value_i, col_width = 80) else if (stringr::str_count(value_i, "\n") > 0 || nchar(value_i, type = "width") > 80) estimate_excel_row_height(value_i, col_width = 80) else 18
      }, numeric(1))
      openxlsx::setRowHeights(wb, sh, rows = first_data_row:last_data_row, heights = row_heights)
    }
    openxlsx::freezePane(wb, sh, firstActiveRow = 4)
  }

  if (!is.null(quality_flags)) {
    qf <- clean_excel_df(quality_flags)
    write_simple_sheet(wb, "Data Quality Flags", "Data Quality Flags", qf, header_style, body_style, title_style, link_style, add_index_row, "Detailed data quality flags generated by the current rule set", widths = c(28,28,22,14,34,75))
    qfs <- clean_excel_df(quality_flag_summary(quality_flags))
    write_simple_sheet(wb, "Quality Flag Summary", "Quality Flag Summary", qfs, header_style, body_style, title_style, link_style, add_index_row, "Summary counts of quality flags by severity and check type", widths = c(18,28,15))
    write_simple_sheet(wb, "Missingness Review", "Missingness Review", dplyr::filter(qf, check_type == "Missingness"), header_style, body_style, title_style, link_style, add_index_row, "Filtered review of missingness-related quality flags", widths = c(28,28,22,14,34,75))
    write_simple_sheet(wb, "Numeric Review", "Numeric Review", dplyr::filter(qf, check_type == "Numeric review"), header_style, body_style, title_style, link_style, add_index_row, "Filtered review of numeric outlier-related quality flags", widths = c(28,28,22,14,34,75))
    write_simple_sheet(wb, "Sentinel Values Review", "Sentinel Values Review", dplyr::filter(qf, check_type %in% c("Sentinel values", "Date review")), header_style, body_style, title_style, link_style, add_index_row, "Filtered review of sentinel values and sentinel date flags", widths = c(28,28,22,14,34,75))
    write_simple_sheet(wb, "Cardinality Review", "Cardinality Review", dplyr::filter(qf, check_type == "Cardinality"), header_style, body_style, title_style, link_style, add_index_row, "Filtered review of cardinality-related quality flags", widths = c(28,28,22,14,34,75))
  }

  idx <- dplyr::bind_rows(index_rows)
  if (nrow(idx) > 0) {
    idx_out <- tibble::tibble(`Go to Sheet` = vapply(seq_len(nrow(idx)), function(i) excel_hyperlink_formula(idx$Sheet[i], idx$Sheet[i]), character(1)), Description = idx$Description)
    openxlsx::writeData(wb, "Index", idx_out, startRow = 3, startCol = 1, headerStyle = header_style)
    openxlsx::writeFormula(wb, "Index", x = idx_out$`Go to Sheet`, startRow = 4, startCol = 1)
    openxlsx::addStyle(wb, "Index", link_style, rows = 4:(3 + nrow(idx_out)), cols = 1, gridExpand = TRUE, stack = TRUE)
    openxlsx::addStyle(wb, "Index", body_style, rows = 4:(3 + nrow(idx_out)), cols = 2, gridExpand = TRUE, stack = TRUE)
  }
  openxlsx::setColWidths(wb, "Index", cols = 1:2, widths = c(35, 85))
  openxlsx::freezePane(wb, "Index", firstActiveRow = 3)
  openxlsx::saveWorkbook(wb, file, overwrite = TRUE)
}
